# Source: root/templates/root.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: apps/
    repoURL: https://github.com/0xByteLeon/kube-argocd-go.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

  ignoreDifferences:
    - group: monitoring.coreos.com
      kind: ServiceMonitor
      jqPathExpressions:
        - .metadata.annotations