apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: third-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/0xByteLeon/kube-argocd-go.git
    path: apps/third-app
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true