argo-cd:
  dex:
    enabled: false
  server:
    service:
      type: ClusterIP
    extraArgs:
      - --insecure
    config:
      repositories: |
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm